---
- name: Install nginx Ubuntu/CentOS
  hosts: all
  become: yes

  vars:

  tasks:
  - name: Show OS version
    debug: var=ansible_os_family
  
  - block: 
    - name: Install nginx & Monit server
      apt: name=nginx state=latest
      apt: name=monit state=latest
      service: name=nginx # Enable nginx server
      
  when: ansible_os_family == "Debian"

  - block:
    - name: Install nginx CentOS
      yum: name=nginx state=latest
      yum: name=monit state=latest
      service: name=nginx # Enable nginx server
  when: ansible_os_family == "RedHat"
