---
- name: Install nginx Ubuntu/CentOS
  hosts: all
  become: yes

  vars:

  tasks:
  - name: Show OS version
    debug: var=ansible_os_family
  
  - block: 
    - name: Install nginx & Monit server
      apt: name={{ item }} state=latest
    with_items:
        - nginx
        - monit  
      service: name=nginx # Enable nginx server
      
  when: ansible_os_family == "Debian"

  - block:
    - name: Install nginx CentOS
      yum: name= {{ item }} state=latest
  with_items:
      - nginx
      - monit
      yum: name=monit state=latest
      service: name=nginx # Enable nginx server
  when: ansible_os_family == "RedHat"
